kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: {{CLUSTER_NAME}}
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /var/run/docker.sock
        containerPath: /var/run/docker.sock
